# This workflow is triggered on pushes to the repository.
name: Flutter Build CI
on:
  push:
    branches:
      - main
    
# on: push
jobs:
  build:
    # This job will run on macOS virtual machine
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta', 'stable'
          flutter-version: '2.10.3'
      - run: | 
          flutter clean
          flutter pub get
          flutter build apk --split-per-abi
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
